/**
 * Generate formatted digital receipt data for financial transactions
 */

const numberToWords = (num) => {
  const a = ['', 'One ', 'Two ', 'Three ', 'Four ', 'Five ', 'Six ', 'Seven ', 'Eight ', 'Nine ', 'Ten ', 'Eleven ', 'Twelve ', 'Thirteen ', 'Fourteen ', 'Fifteen ', 'Sixteen ', 'Seventeen ', 'Eighteen ', 'Nineteen '];
  const b = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];

  if ((num = num.toString()).length > 9) return 'Overflow';
  const n = ('000000000' + num).substr(-9).match(/^(\d{2})(\d{2})(\d{2})(\d{1})(\d{2})$/);
  if (!n) return '';
  let str = '';
  str += Number(n[1]) !== 0 ? (a[Number(n[1])] || b[n[1][0]] + ' ' + a[n[1][1]]) + 'Crore ' : '';
  str += Number(n[2]) !== 0 ? (a[Number(n[2])] || b[n[2][0]] + ' ' + a[n[2][1]]) + 'Lakh ' : '';
  str += Number(n[3]) !== 0 ? (a[Number(n[3])] || b[n[3][0]] + ' ' + a[n[3][1]]) + 'Thousand ' : '';
  str += Number(n[4]) !== 0 ? (a[Number(n[4])] || b[n[4][0]] + ' ' + a[n[4][1]]) + 'Hundred ' : '';
  str += Number(n[5]) !== 0 ? ((str !== '') ? 'and ' : '') + (a[Number(n[5])] || b[n[5][0]] + ' ' + a[n[5][1]]) : '';
  return str.trim() ? `${str.trim()} Rupees Only` : 'Zero Rupees Only';
};

function formatReceipt({
  receiptNumber,
  transactionId,
  groupName,
  groupCode,
  villageTown,
  district,
  memberName,
  memberNumber,
  amount,
  purpose,
  paymentMethod,
  date,
  recordedByName,
  notes = '',
}) {
  return {
    receiptNumber,
    transactionId,
    platform: 'SmartSHG Digital Community Finance',
    group: {
      name: groupName,
      code: groupCode,
      location: `${villageTown}, ${district}`,
    },
    member: {
      name: memberName,
      number: memberNumber || 'N/A',
    },
    payment: {
      amount,
      amountInWords: numberToWords(Math.floor(amount)),
      purpose,
      method: paymentMethod,
      date: new Date(date).toLocaleDateString('en-IN', {
        day: '2-digit',
        month: 'short',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      }),
      notes,
    },
    issuer: {
      recordedBy: recordedByName,
      digitalVerification: 'VERIFIED_RECORD',
    },
    disclaimer: 'This is a digital record generated by SmartSHG for group accounting. This is an internal self-help group record and not an official government treasury receipt.',
  };
}

module.exports = {
  formatReceipt,
  numberToWords,
};
